name: OSS

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Hexo
        run: npm install hexo-cli -g

      # generate hexo blog website.
      - name: Generate
        run: hexo generate

      - name: upload files to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
            accessKeyId: ${{ secrets.OSS_ACCESS_ID }}
            accessKeySecret: ${{ secrets.OSS_ACCESS_SECRET }}
            bucket: ssrcoder-blog
            endpoint: oss-cn-beijing.aliyuncs.com
            folder: public
